[env:emax_900_tx_oled]
custom_meshtastic_hw_model = 144
custom_meshtastic_hw_model_slug = EMAX_900_TX_OLED
custom_meshtastic_architecture = esp32
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = Emax 900 OLED TX
custom_meshtastic_tags = Emax, ExpressLRS

extends = esp32_base
board = esp32doit-devkit-v1
build_flags =
  ${esp32_base.build_flags}
  -DEMAX_900_TX_OLED
  -DVTABLES_IN_FLASH=1
  -DCONFIG_DISABLE_HAL_LOCKS=1
  -O2
  -I variants/esp32/emax_900_tx_oled
board_build.partitions = no_ota.csv
board_build.f_cpu = 240000000L
upload_protocol = esptool
upload_speed = 460800
